version: "3"
services:
    nginx:
        image: nginx:1.21.5-alpine
        ports:
            - 8000:80
        volumes:
            - ./:/var/www/html/
            - ./docker/nginx/conf.d/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app

    app:
        build:
            context: ./
            dockerfile: ./docker/app/dev.Dockerfile
        volumes:
            - ./:/var/www/html/
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini.
        depends_on:
            - db

    db:
        image: mysql:8
        platform: linux/x86_64
        # command: mysqld --sql-mode=''
        environment:
            MYSQL_ROOT_PASSWORD: 123
            MYSQL_DATABASE: laravel
        ports:
            - 3306:3306

    myadmin:
        image: phpmyadmin:5
        environment:
            PMA_HOST: db
            PMA_USER: root
            PMA_PASSWORD: 123
        ports:
            - 9000:80
        depends_on:
            - db
